export const SET_TOP_ALBUMS = 'SET_FAVORITES';
export const UPDATE_FAVORITE_RANKS = 'UPDATE_FAVORITE_RANKS';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const SET_ERROR = 'SET_ERROR';
